LANGUAGES = {
    "UA": {
        "add_filter2": "+ Додати другий критерій",
        "analyze_responses": "Аналіз відповідей",
        "analyze_tab": "Аналіз",
        "app_title": "Аналіз результатів опитувань студентів (Google Forms)",
        "apply_filters": "Застосувати фільтри",
        "chart_title": "Розподіл відповідей",
        "chose_format": "Оберіть формат для завантаження: 👇",
        "count": "Кількість",
        "detailed_view": "Детальний перегляд",
        "developer": "Розробник: Каптар Діана (студентка МПУіК)",
        "distribution": "Розподіл",
        "download_demo_btn": "Завантажити демо-файл (EN)",
        "download_docx": "Завантажити Word",
        "download_excel": "Завантажити Excel",
        "download_pdf": "Завантажити PDF",
        "download_pptx": "Завантажити PowerPoint",
        "download_zip": "Завантажити ZIP",
        "error": "Помилка",
        "error_font": "Помилка завантаження шрифту. Будь ласка, перевірте підключення до інтернету та перезавантажте сторінку.",
        "error_font2": "Якщо помилка повторюється, спробуйте завантажити звіт у форматі Word або Excel.",
        "export_reports": "Експорт звітів",
        "export_tab": "Експорт",
        "filter_section": "2. Фільтрація",
        "filter1": "Критерій 1",
        "filter1_value": "Значення 1",
        "filter2": "Критерій 2",
        "filter2_value": "Значення 2",
        "first_row_error": "Помилка: перший рядок не може бути більшим за останній.",
        "found_results": "Знайдено",
        "full_summary": "Повний огляд всіх питань",
        "in_work": "В роботі",
        "load_file_left": "👈 Завантажте файл у меню зліва.",
        "loaded": "Завантажено",
        "made_by": "Розроблено в рамках дипломної роботи",
        "no_data": "Завантажено: 0 анкет.",
        "no_results": "Анкет не знайдено.",
        "option": "Варіант відповіді",
        "parameter": "Параметр",
        "percentage": "Відсоток",
        "please_select": "Будь ласка, оберіть",
        "process_btn": "Обробити",
        "processed_surveys": "Оброблено анкет",
        "range": "Діапазон рядків",
        "range_error": "Помилка діапазону рядків",
        "raw_data": "Вихідні_дані",
        "read_error": "Помилка читання файлу",
        "report_footer": "Створено за допомогою додатку студентки МПУіК - Каптар Діани.",
        "report_footer2": "Керівник проєкту – доцент Фратавчан Валерій Григорович.",
        "report_title": "Звіт з аналізу результатів опитування",
        "reset_btn": "Скинути",
        "result": "Результат",
        "row_slider": "Оберіть діапазон рядків для обробки",
        "rows": "Рядки",
        "select_parameters": "Оберіть параметри.",
        "select_question": "Оберіть питання",
        "setup_filters": "Налаштувати фільтри",
        "summary": "Підсумки",
        "supervisor": "Керівник проєкту: доцент Фратавчан Валерій Григорович | 2025 р.",
        "survey_details": "Деталі анкети",
        "surveys": "анкет",
        "target_question": "Питання для аналізу",
        "technical_info": "Технічна_інформація",
        "thank_you": "Дякую за увагу!",
        "total_surveys": "Завантажено анкет",
        "university_name": "Чернівецький національний університет імені Юрія Федьковича",
        "upload_label": "1. Завантаження Excel-файлів (.xlsx)",
        "value": "Значення",
        "value_error": "Помилка значення",
        "variant": "Варіант відповіді",
        "view_data": "Переглянути дані",
        "page_title": "Обробка результатів",

    },
    "EN": {
        "add_filter2": "+ Add second filter",
        "analyze_responses": "Analyze responses",
        "analyze_tab": "Analysis",
        "app_title": "Survey Analytics (Google Forms)",
        "apply_filters": "Apply filters",
        "chart_title": "Distribution of responses",
        "chose_format": "Choose format for download: 👇",
        "count": "Count",
        "detailed_view": "Detailed view",
        "developer": "Developer: Diana Kaptar (student of MPUiK)",
        "distribution": "Distribution",
        "download_demo_btn": "Download demo file (EN)",
        "download_docx": "Download Word",
        "download_excel": "Download Excel",
        "download_pdf": "Download PDF",
        "download_pptx": "Download PowerPoint",
        "download_zip": "Download ZIP",
        "error": "Error",
        "error_font": "Font download error. Please check your internet connection and reload the page.",
        "error_font2": "If the error persists, try downloading the report in Word or Excel format.",
        "export_reports": "Export reports",
        "export_tab": "Export",
        "filter_section": "2. Filtering",
        "filter1": "Filter 1",
        "filter1_value": "Value 1",
        "filter2": "Filter 2",
        "filter2_value": "Value 2",
        "first_row_error": "Error: the first row cannot be greater than the last row.",
        "found_results": "Found",
        "full_summary": "Full overview of all questions",
        "in_work": "In progress",
        "load_file_left": "👈 Upload a file in the menu on the left.",
        "loaded": "Loaded",
        "made_by": "Developed as part of the diploma project",
        "no_data": "Loaded: 0 surveys.",
        "no_results": "No surveys found.",
        "option": "Answer option",
        "parameter": "Parameter",
        "percentage": "Percentage",
        "please_select": "Please select",
        "process_btn": "Process",
        "processed_surveys": "Processed surveys",
        "range": "Row range",
        "range_error": "Row range error",
        "raw_data": "Raw_data",
        "report_footer": "Created with the help of the application by Diana Kaptar, a student of MPUiK.",
        "report_footer2": "Project supervisor – Associate Professor Valeriy Fratavchan.",
        "report_title": "Survey Results Analysis Report",
        "reset_btn": "Reset",
        "result": "Result",
        "row_slider": "Select the range of rows to process",
        "rows": "Rows",
        "select_parameters": "Select parameters.",
        "select_question": "Select a question",
        "setup_filters": "Set up filters",
        "summary": "Summary",
        "supervisor": "Project supervisor: Associate Professor Valeriy Fratavchan | 2025",
        "survey_details": "Survey details",
        "surveys": "surveys",
        "target_question": "Question for analysis",
        "technical_info": "Technical_info",
        "thank_you": "Thank you for your attention!",
        "total_surveys": "Loaded surveys",
        "university_name": "Yuriy Fedkovych Chernivtsi National University",
        "upload_label": "1. Upload Excel files (.xlsx)",
        "value": "Value",
        "value_error": "Value error",
        "variant": "Answer option",
        "view_data": "View data",
        "page_title": "Survey Results Processing",
    },

    "RO": {
        "add_filter2": "+ Adăugați al doilea criteriu",
        "analyze_responses": "Analiza răspunsurilor",
        "analyze_tab": "Analiză",
        "app_title": "Analiza rezultatelor sondajelor studenților (Google Forms)",
        "apply_filters": "Aplică filtrele",
        "chart_title": "Distribuția răspunsurilor",
        "chose_format": "Alegeți formatul pentru descărcare: 👇", 
        "count": "Număr",
        "detailed_view": "Vizualizare detaliată",
        "developer": "Dezvoltator: Diana Kaptar (studentă la MPUiK)",
        "distribution": "Distribuție",
        "download_demo_btn": "Descărcați fișierul demo (EN)",
        "download_docx": "Descărcați Word",
        "download_excel": "Descărcați Excel",
        "download_pdf": "Descărcați PDF",
        "download_pptx": "Descărcați PowerPoint",
        "download_zip": "Descărcați ZIP",
        "error": "Eroare",
        "error_font": "Eroare la descărcarea fontului. Vă rugăm să verificați conexiunea la internet și să reîncărcați pagina.",
        "error_font2": "Dacă eroarea persistă, încercați să descărcați raportul în format Word sau Excel.",
        "export_reports": "Exportați rapoartele",
        "export_tab": "Export",
        "filter_section": "2. Filtrare",
        "filter1": "Criteriu 1",
        "filter1_value": "Valoare 1",
        "filter2": "Criteriu 2",
        "filter2_value": "Valoare 2",
        "first_row_error": "Eroare: primul rând nu poate fi mai mare decât ultimul.",
        "found_results": "Găsit",
        "full_summary": "Prezentare generală completă a tuturor întrebărilor",
        "in_work": "În lucru",
        "load_file_left": "👈 Încărcați un fișier",
        "loaded": "Încărcat",
        "made_by": "Dezvoltat în cadrul proiectului de diplomă",
        "no_data": "Încărcat: 0 chestionare.",
        "no_results": "Nu s-au găsit chestionare.",
        "option": "Opțiune de răspuns",
        "parameter": "Parametru",
        "percentage": "Procent",
        "please_select": "Vă rugăm să selectați",
        "process_btn": "Procesează",
        "processed_surveys": "Chestionare procesate",
        "range": "Interval de rânduri",
        "range_error": "Eroare la intervalul de rânduri",
        "raw_data": "Date_brute",
        "read_error": "Eroare la citirea fișierului",
        "report_footer": "Creat cu ajutorul aplicației de către Diana Kaptar, studentă la MPUiK.",
        "report_footer2": "Coordonatorul proiectului – Conferențiar universitar Valeriy Fratavchan.",
        "report_title": "Raport de analiză a rezultatelor sondajului",
        "reset_btn": "Resetează",
        "result": "Rezultat",
        "row_slider": "Selectați intervalul de rânduri pentru procesare",
        "rows": "Rânduri",
        "select_parameters": "Selectați parametrii.",
        "select_question": "Selectați întrebările",
        "setup_filters": "Configurați filtrele",
        "summary": "Rezumat",
        "supervisor": "Supervizor de proiect: Profesor asociat Valeriy Fratavchan | 2025",
        "survey_details": "Detalii sondaj",
        "surveys": "sondaj",
        "target_question": "Întrebare pentru analiză",
        "technical_info": "Informații tehnice",
        "thank_you": "Vă mulțumim pentru atenție!",
        "total_surveys": "Sondaje încărcate",
        "university_name": "Universitatea Națională „Yuriy Fedkovych” din Cernăuți",
        "upload_label": "1. Încărcați fișiere Excel (.xlsx)",
        "value": "Valoare",
        "value_error": "Eroare de valoare",
        "variant": "Opțiune de răspuns",
        "view_data": "Vizualizați datele",
        "page_title": "Prelucrarea rezultatelor sondajului",
    },

    "PL":{
        "add_filter2": "+ Dodaj drugi filtr",
        "analyze_responses": "Analiza odpowiedzi",
        "analyze_tab": "Analiza",
        "app_title": "Analiza ankiet (Google Forms)",
        "apply_filters": "Zastosuj filtry",
        "chart_title": "Rozkład odpowiedzi",
        "chose_format": "Wybierz format do pobrania: 👇",
        "count": "Liczba",
        "detailed_view": "Widok szczegółowy",
        "developer": "Twórca: Diana Kaptar (studentka MPUiK)",
        "distribution": "Rozkład",
        "download_demo_btn": "Pobierz plik demonstracyjny (EN)",
        "download_docx": "Pobierz plik Word",
        "download_excel": "Pobierz plik Excel",
        "download_pdf": "Pobierz plik PDF",
        "download_pptx": "Pobierz plik PowerPoint",
        "download_zip": "Pobierz plik ZIP",
        "error": "Błąd",
        "error_font": "Błąd pobierania czcionki. Sprawdź połączenie internetowe i odśwież stronę.",
        "error_font2": "Jeśli błąd nadal występuje, spróbuj pobrać raport w formacie Word lub Excel.",
        "export_reports": "Eksportuj raporty",
        "export_tab": "Eksportuj",
        "filter_section": "2. Filtrowanie",
        "filter1": "Filtr 1",
        "filter1_value": "Wartość 1",
        "filter2": "Filtr 2",
        "filter2_value": "Wartość 2",
        "first_row_error": "Błąd: pierwszy wiersz nie może być większy niż ostatni wiersz.",
        "found_results": "Znaleziono",
        "full_summary": "Pełny przegląd wszystkich pytań",
        "in_work": "W trakcie",
        "load_file_left": "👈 Prześlij plik w menu po lewej stronie.",
        "loaded": "Załadowano",
        "made_by": "Opracowano w ramach pracy dyplomowej",
        "no_data": "Załadowano: 0 ankiet.",
        "no_results": "Nie znaleziono ankiet.",
        "option": "Opcja odpowiedzi",
        "parameter": "Parametr",
        "percentage": "Procent",
        "please_select": "Proszę wybrać",
        "process_btn": "Przetwórz",
        "processed_surveys": "Przetworzone ankiety",
        "range": "Zakres wierszy",
        "range_error": "Błąd zakresu wierszy",
        "raw_data": "Dane surowe",
        "report_footer": "Stworzono przy pomocy aplikacji autorstwa Diany Kaptar, studentki MPUiK.",
        "report_footer2": "Opiekun projektu – profesor nadzwyczajny Valeriy Fratavchan.",
        "report_title": "Raport z analizy wyników ankiet",
        "reset_btn": "Resetuj",
        "result": "Wynik",
        "row_slider": "Wybierz zakres wierszy do przetworzenia",
        "rows": "Wiersze",
        "select_parameters": "Wybierz parametry.",
        "select_question": "Wybierz pytanie",
        "setup_filters": "Ustaw filtry",
        "summary": "Podsumowanie",
        "supervisor": "Kierownik projektu: profesor nadzwyczajny Valeriy Fratavchan | 2025",
        "survey_details": "Szczegóły ankiety",
        "surveys": "ankiety",
        "target_question": "Pytanie do analizy",
        "technical_info": "Informacje techniczne",
        "thank_you": "Dziękujemy za uwagę!",
        "total_surveys": "Załadowane ankiety",
            "university_name": "Narodowy Uniwersytet im. Jurija Fedkowicza w Czerniowcach",
        "upload_label": "1. Prześlij pliki Excel (.xlsx)",
        "value": "Wartość",
        "value_error": "Błąd wartości",
        "variant": "Opcja odpowiedzi",
        "view_data": "Wyświetl dane",
        "page_title": "Przetwarzanie wyników ankiety",
    }
}
